"""
app.py - The Pipeline Infrastructure
DO NOT EDIT THIS FILE unless you are modifying the core GCS handling logic.
Biologists: Please place your code in `model.py`.
"""

import os
import signal
import json
import uuid
import shutil
from flask import Flask, request, Response, jsonify
from flask_cors import CORS
from waitress import serve
from google.cloud import storage

# Import the user's custom model logic
import model

app = Flask(__name__)
CORS(app)

def handle_sigterm(*args):
    """
    Handle forceful container termination gracefully.
    
    Parameters
    ----------
    *args : tuple
        Variable length argument list passed by the signal handler.
    """
    print("Received SIGTERM, shutting down gracefully...")
    for item in os.listdir("/tmp"):
        if item.startswith("run_"):
            shutil.rmtree(os.path.join("/tmp", item), ignore_errors=True)
    os._exit(0)

def download_gcs_uri(client: storage.Client, uri: str, destination: str):
    """
    Downloads a single GCS file to a local destination.
    
    Parameters
    ----------
    client : storage.Client
        The instantiated Google Cloud Storage client.
    uri : str
        The full gs:// URI of the file to download.
    destination : str
        The local file path where the file should be saved.
    """
    bucket_name = uri.replace("gs://", "").split("/")[0]
    blob_path = "/".join(uri.replace("gs://", "").split("/")[1:])
    bucket = client.bucket(bucket_name)
    blob = bucket.blob(blob_path)
    blob.download_to_filename(destination)

def upload_gcs_uri(client: storage.Client, local_path: str, uri: str, content_type="video/mp4"):
    """
    Uploads a local file to a GCS destination.
    
    Parameters
    ----------
    client : storage.Client
        The instantiated Google Cloud Storage client.
    local_path : str
        The local file path of the file to upload.
    uri : str
        The full gs:// URI destination.
    content_type : str, optional
        The MIME type of the file being uploaded (default is "video/mp4").
    """
    bucket_name = uri.replace("gs://", "").split("/")[0]
    blob_path = "/".join(uri.replace("gs://", "").split("/")[1:])
    bucket = client.bucket(bucket_name)
    blob = bucket.blob(blob_path)
    blob.upload_from_filename(local_path, content_type=content_type)

@app.route("/isalive")
def is_alive():
    """Vertex AI liveness/readiness probe."""
    return Response(status=200)

@app.route("/predict", methods=["POST"])
def predict():
    storage_client = storage.Client()
    
    try:
        data = request.get_json()
        if not data:
            return jsonify({"error": "Missing or invalid JSON payload"}), 400
        
        instances = data.get("instances")
        if not instances or not isinstance(instances, list):
            return jsonify({"error": "'instances' is required and must be a non-empty list"}), 400
    
        # Extract the global parameters injected by inference_runner.py
        global_params = data.get("parameters", {})
        output_bucket = global_params.get("OUTPUT_BUCKET")
        output_folder = global_params.get("OUTPUT_FOLDER")

        results = []

        for instance in instances:
            run_id = f"run_{uuid.uuid4().hex}"
            run_dir = f"/tmp/{run_id}"
            inputs_dir = os.path.join(run_dir, "inputs")
            os.makedirs(inputs_dir, exist_ok=True)
            
            try:
                config = instance.get("config", {})
                
                # Input Data Parsing
                input_path = instance.get("input_path")
                if not input_path:
                    input_files = instance.get("input_files", [])
                    if input_files:
                        input_path = input_files[0]

                if not input_path:
                    raise ValueError("No valid input file found in instance payload.")

                print(f"[{run_id}] Downloading {input_path} to {inputs_dir}...")
                original_filename = os.path.basename(input_path)
                dest = os.path.join(inputs_dir, original_filename)
                download_gcs_uri(storage_client, input_path, dest)

                # Output Path Reconstruction
                if not output_bucket or not output_folder:
                    raise ValueError("OUTPUT_BUCKET or OUTPUT_FOLDER missing from parameters.")
                
                name_without_ext, _ = os.path.splitext(original_filename)
                new_filename = f"{name_without_ext}.mp4"
                output_file = f"gs://{output_bucket}/{output_folder.strip('/')}/{new_filename}"
                local_output = os.path.join(run_dir, new_filename)

                print(f"[{run_id}] Delegating to model.py for video processing...")
                
                model.run_inference(
                    input_dir=inputs_dir,
                    output_file_path=local_output,
                    config=config
                )
                
                if not os.path.exists(local_output):
                    raise FileNotFoundError(f"model.py finished, but did not create {local_output}")

                # Result Upload
                print(f"[{run_id}] Uploading results to {output_file}...")
                upload_gcs_uri(storage_client, local_output, output_file)
                
                results.append({"status": "success", "output_file": output_file})

            except Exception as inner_e:
                print(f"[{run_id}] Instance processing failed: {str(inner_e)}")
                results.append({"status": "error", "error": str(inner_e)})
                
            finally:
                # Strict Cleanup
                print(f"[{run_id}] Cleaning up workspace {run_dir}...")
                shutil.rmtree(run_dir, ignore_errors=True)

        return jsonify({"predictions": results})
     
    except Exception as e:
        print(f"Error in overall prediction flow: {str(e)}")
        return jsonify({"error": str(e)}), 500 

if __name__ == "__main__":    
    # 360000 seconds = 100 hours. This is the maximum length timeout.
    # Prevents Waitress from closing socket on massive, multi-hour video inference pipelines.
    CHANNEL_TIMEOUT = 360000  
    print("Waitress WSGI Server is starting up...")
    print("Listening on: http://0.0.0.0:8080")
    print(f"Channel timeout set to {CHANNEL_TIMEOUT}s")

    signal.signal(signal.SIGTERM, handle_sigterm)
    serve(app, host="0.0.0.0", port=8080, channel_timeout=CHANNEL_TIMEOUT)
